"""Add has_evolution and evolution_picture_url to card

Revision ID: 68c89a971542
Revises: 
Create Date: 2025-04-02 23:11:00.738478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c89a971542'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_evolution', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('evolution_picture_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('evolution_picture_url')
        batch_op.drop_column('has_evolution')

    # ### end Alembic commands ###
